name: Playwright Tests

on:
  push:
    branches: [main]
  workflow_dispatch:
    inputs:
      environment:
        description: "Select Environment"
        required: true
        default: "QA"
        type: choice
        options:
          - QA
          - UAT

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment || 'QA' }}

    env:
      ENV: ${{ secrets.ENV }}
      PARALLEL: ${{ secrets.PARALLEL }}
      HEADLESS: ${{ secrets.HEADLESS }}
      RETRY: ${{ secrets.RETRY }}
      URL: ${{ secrets.URL }}
      SPECIFIED_TIMEOUT: ${{ secrets.SPECIFIED_TIMEOUT }}
      WORKERS: ${{ secrets.WORKERS }}
      TEST_TIMEOUT: ${{ secrets.TEST_TIMEOUT }}
      EXPECT_TIMEOUT: ${{ secrets.EXPECT_TIMEOUT }}
      ACTION_TIMEOUT: ${{ secrets.ACTION_TIMEOUT }}
      NAV_TIMEOUT: ${{ secrets.NAV_TIMEOUT }}

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report-${{ github.event.inputs.environment || 'QA' }}
          path: playwright-report/
          retention-days: 30
